name: Test Reusable

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths-ignore:
      - 'charts/**'
      - '**.md'
      - 'docs/**'
      - 'book.toml'
      - '.github/dependabot.yml'
      - '.github/workflows/helm-release.yml'
      - '.github/workflows/mdbook.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/rust-clippy.yml'
  pull_request:
    branches: [ main ]
  workflow_call:

concurrency:
  group: "shoebox"
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from reusable workflow!"
